config/routes.rb
Rails.application.routes.draw do
  root to: 'cats#index'
  resources :cats
  
  resources :cat_rental_requests, only: [:new, :create, :destroy] do
    get 'approve'
    get 'deny'
  end
  
  resources :users, only: [:create, :new, :show]
  
  resource :session, only: [:create, :new, :destroy]
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  user_name       :string(255)      not null
#  password_digest :string(255)      not null
#  session_token   :string(255)      not null
#  created_at      :datetime
#  updated_at      :datetime
#
require 'bcrypt'

class User < ActiveRecord::Base
  validates :user_name, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  
  after_initialize :session_token_exists
  
  attr_reader :password
  
  has_many :cats
  has_many :requests, class_name: 'CatRentalRequest', foreign_key: :user_id
  
  has_many :cats_requests, through: :cats, source: :cat_rental_requests
  
  def self.find_by_credentials(user_name, password)
    user = User.find_by(user_name: user_name)
    return nil if user.nil?      
    user.is_password?(password) ? user : nil
  end
    
  def session_token_exists
    self.session_token ||= SecureRandom::urlsafe_base64
  end
  
  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64
    self.save!    
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)  
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_current_user!, except: [:create, :new]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login!(@user)
      render :show
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new  
    end
  end

  def show
    @user = User.find(params[:id])
  end
  
  private
  def user_params
    params.require(:user).permit(:user_name, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(SecureRandom::urlsafe_base64(16))
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, class: "gravatar")
  end
end

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Create a user account!</h1>

<form action="<%= users_url %>" method="POST" role="form">
  
  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">
  
 <label for="user_user_name">Username</label>
 <input type="text" 
        name="user[user_name]" 
        value="<%= @user.user_name %>" 
        id="user_user_name">
 <br>
<label for="user_password">Password</label>
<input type="password" 
       name="user[password]"  
       id="user_password">
<br>
<input type="submit" value="Create account!">
 </form>

app/views/users/show.html.erb
<h1>Hello <%= @user.user_name %>!</h1>
<%= gravatar_for @user %>