config/routes.rb
Rails.application.routes.draw do
  root to: 'cats#index'
  resources :cats
  
  resources :cat_rental_requests, only: [:new, :create, :destroy] do
    get 'approve'
    get 'deny'
  end
  
  resources :users, only: [:create, :new, :show]
  
  resource :session, only: [:create, :new, :destroy]
end

app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :integer          not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string(255)      default("PENDING"), not null
#  created_at :datetime
#  updated_at :datetime
#

class CatRentalRequest < ActiveRecord::Base
  STATUS = ["PENDING", "APPROVED", "DENIED"]
  
  validates :cat_id, :user_id, presence: true
  validates :status, presence: true, inclusion: {in: STATUS}
  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :no_overlapping_approved_requests 
  validate :end_date_cannot_be_before_start_date
  
  belongs_to :cat
  belongs_to :user
  
  def self.order_by_start_date
    order(:start_date)
  end
  
  def approve!
    overlaps = self.overlapping_approved_requests.length
    if overlaps > 0
      raise 'HELL'
    else
      CatRentalRequest.transaction do 
        self.status = "APPROVED"
        self.save
        self.overlapping_pending_requests.each do |request|
          request.deny!
        end
      end
    end
  end
  
  def pending?
    self.status == 'PENDING'
  end
  
  def deny!
    self.status = "DENIED"
    self.save!
  end

  def overlapping_requests
    query = <<-SQL
      (
      (start_date BETWEEN '#{self.start_date}' AND '#{self.end_date}')
    OR
      (end_date BETWEEN '#{self.start_date}' AND '#{self.end_date}')
    OR
      (start_date >= '#{self.start_date}' AND end_date <= '#{self.end_date}')
    OR
      (start_date <= '#{self.start_date}' AND end_date >= '#{self.end_date}')
      )
    AND
      cat_id = '#{self.cat_id}'
    SQL
        #returns all requests that would be overlapping with our new request
    CatRentalRequest.select('cat_rental_requests.*').where(query)
  end
  
  def overlapping_approved_requests
    overlapping_requests.where("status = 'APPROVED'")
  end
  
  def overlapping_pending_requests
    overlapping_requests.where("status = 'PENDING'")
  end

  
  def no_overlapping_approved_requests
    unless start_date.blank? || end_date.blank? || cat_id.blank? || self.status == 'DENIED'
      if overlapping_approved_requests.length > 0
        errors[:requests] << "can't overlap"
      end
    end
  end
  
  def end_date_cannot_be_before_start_date
    unless start_date.blank? || end_date.blank?
      if start_date > end_date
        errors[:requests] << "can't have invalid dates"
      end
    end
  end
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  before_action :require_current_user!, except: [:new, :create]
  
  def new
    @cat_rental_request = CatRentalRequest.new
    @cats = Cat.all
  end
  
  def create
    @cat_rental_request = CatRentalRequest.new(cat_rental_request_params)
    @cats = Cat.all
    @cat_rental_request.user_id = current_user.id
    if @cat_rental_request.save
      redirect_to cat_url(@cat_rental_request.cat)
    else
      flash.now[:errors] = @cat_rental_request.errors.full_messages
      render :new
    end
  end
  
  def destroy
    @cat_rental_request = CatRentalRequest.find(params[:id])
    user = @cat_rental_request.user
    if user == current_user 
      @cat_rental_request.destroy
      redirect_to cat_url(@cat_rental_request.cat)
    else
      render json: "Hey you cannot delete requests of others!!!"
    end
  end
   
   
  def approve
    @cat_rental_request = current_user.cats_requests.find_by_id(params[:cat_rental_request_id])
    if @cat_rental_request.nil?
      render json: "You are not the owner of this cat..."
    else
      @cat_rental_request.approve!
      redirect_to cat_url(@cat_rental_request.cat)
    end
  end
  
  def deny
    @cat_rental_request = current_user.cats_requests.find_by_id(params[:cat_rental_request_id])
    if @cat_rental_request.nil?
      render json: "You are not the owner of this cat..."
    else
      @cat_rental_request.deny!
      redirect_to cat_url(@cat_rental_request.cat)
    end
  end
  
  private
  
  def cat_rental_request_params
    params.require(:cat_rental_request).permit(:cat_id, :start_date, :end_date)
  end
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/views/cat_rental_requests/new.html.erb
<div class="col-md-4 col-md-offset-4">
<h1 class="text-center">Make a request!</h1>

<%= render 'shared/error' %>


<form action="<%= cat_rental_requests_url %>" method="POST">
  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">
  
  <label for="cat_rental_request_cat_id">Cat</label>
  <select id="cat_rental_request_cat_id" name="cat_rental_request[cat_id]" class="form-control">
    <option></option>
    <% @cats.each do |cat| %>
      <option value="<%= cat.id %>"
        <%= "selected" if @cat_rental_request.cat_id == cat.id %>
        ><%= cat.name %></option>
    <% end %>
  </select>
  <br>
  
  <label for="cat_rental_request_start_date">Start Date</label>
  <% today = Date.today%>
  <input type="date"
         name="cat_rental_request[start_date]"
         value="<%= @cat_rental_request.start_date %>"
         min='<%= "#{today.year}-#{today.month}-#{today.day}" %>'
         id="cat_rental_request_start_date"
         class="form-control" >
  <br>
  
  <label for="cat_rental_request_end_date">End Date</label>
  <% today = Date.today%>
  <input type="date"
         name="cat_rental_request[end_date]"
         value="<%= @cat_rental_request.end_date %>"
         min='<%= "#{today.year}-#{today.month}-#{today.day}" %>' 
         id="cat_rental_request_end_date" 
         class="form-control">
  <br>
  
  <button type="submit" class="btn btn-primary btn-lg col-md-offset-3">Make the request!</button>
</form>
</div>