config/routes.rb
Rails.application.routes.draw do
  root to: 'cats#index'
  resources :cats
  
  resources :cat_rental_requests, only: [:new, :create, :destroy] do
    get 'approve'
    get 'deny'
  end
  
  resources :users, only: [:create, :new, :show]
  
  resource :session, only: [:create, :new, :destroy]
end

app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :integer          not null, primary key
#  birth_date  :date             not null
#  color       :string(255)      not null
#  name        :string(255)      not null
#  sex         :string(255)      not null
#  description :text
#  created_at  :datetime
#  updated_at  :datetime
#  user_id     :integer          not null
#

class Cat < ActiveRecord::Base
  SEX = ["M", "F"]
  COLOR = ["black", "brown", "gray", "white", "chocolate", "calico", "tortie"]
  
  validates :sex, presence: true, inclusion: { in: SEX }
  validates :color, presence: true, inclusion: { in: COLOR }
  validates :birth_date, :user_id, :name, presence: true
  validate :on_or_before_today
  
  has_many :cat_rental_requests, dependent: :destroy
  
  belongs_to :owner, class_name: 'User', foreign_key: :user_id
  

  def on_or_before_today
    if !self.birth_date.nil? && self.birth_date > Date.today 
      errors[:birth_date] << "is invalid"
    end
  end
  
  def age
    (Date.today - self.birth_date).numerator/365
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :require_current_user!, only: [:create, :edit, :update, :destroy]
  
  def index
    @cats = Cat.all
    render :index
  end
  
  def show
    @cat = Cat.find(params[:id])
    @requests = @cat.cat_rental_requests.order_by_start_date
    render :show    
  end
  
  def new
    @cat = Cat.new
    render :new    
  end
  
  def create
    @cat = Cat.new(cat_params)
    @cat.user_id = current_user.id
    if @cat.save
      redirect_to cat_url(@cat)
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :new
    end    
  end
  
  def edit
    @cat = current_user.cats.find_by_id(params[:id])
    @cat.nil? ? (render json: "You don't own the cat!") : (render :edit)
  end
  
  def update
    @cat = Cat.find(params[:id])
    
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      flash.now[:errors] = @cat.errors.full_messages
      render :edit
    end
  end
  
  def destroy
    @cat = current_user.cats.find_by_id(params[:id])
    @cat.destroy unless @cat.nil? 
    redirect_to cats_url
  end
  
  private

  def cat_params
    params.require(:cat).permit(:sex, :name, :color, :birth_date, :description, :user_id)
  end
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/edit.html.erb
<%= render 'shared/error.html.erb' %>
<div class="col-md-4 col-md-offset-4">
<h1 class="text-center">Edit a cat!</h1>

<form action="<%= cat_url(@cat) %>" method="POST" role="form">
  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">
    
  <input type="hidden" name="_method" value="PATCH">

  <div class="form-group">
  <label for="cat_name">Name</label>
  <input type="text" 
        name="cat[name]" 
        id="cat_name" 
        value="<%= @cat.name %>"
        class="form-control"
        placeholder="Name">
  <div>
    
   <fieldset class="sex-fieldset"> 
   <legend class="sex-field">Sex</legend>
        
  <div class="radio form-control">
 
  <% Cat::SEX.each do |sex| %>
    <label for="cat_sex">
    <input type="radio"
           name="cat[sex]"
           value="<%= sex %>"
           <%= "checked" if @cat.sex == sex %>
           id="cat_sex">
      <%= sex == "M" ? "Male" : "Female"%>
    </label>
  <% end %>
</div>
</fieldset>
 
  <label for="cat_color">Color</label>
  <select name="cat[color]" id="cat_color" class="form-control">
    <option></option>
    <% Cat::COLOR.each do |color| %>
      <option 
        value="<%= color %>" 
        <%= "selected" if @cat.color == color %>>
        <%= color %>
      </option>
    <% end %>  
  </select>
  <br>
  
  <label for="cat_birth_date">Birthdate</label>
  <% today = Date.today%>
  <input type="date"
         name="cat[birth_date]"
         value="<%= @cat.birth_date %>"
         max="<%= "#{today.year}-#{today.month}-#{today.day}"%>"
         class="form-control"
         id="cat_birth_date" >
  <br>
  
  <label for="cat_description">Description</label>
  <textarea name="cat[description]"
            id="cat_description"
            class="form-control"
            placeholder="Enter description"><%= @cat.description %></textarea>
  <br>
  <div class="gravatar_edit">
    <%= gravatar_for @cat %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
  <button type="submit" class="btn btn-primary btn-lg col-md-offset-4">Edit the cat!</button>
</form>
</div>

app/views/cats/index.html.erb
<div class="col-md-4 col-md-offset-4">
<h1 class="text-center">All Cats</h1>

<ul class="cats">
  <% @cats.each do |cat| %>
  <li>
    <%= gravatar_for(cat) %>      
    <%= link_to cat.name, cat_url(cat), class: "col-md-offset-1" %>
  <li>
  <% end %>


<%= link_to "Add a new cat!", new_cat_url, class: "btn btn-large btn-primary col-md-offset-3"%>
</div>

app/views/cats/new.html.erb
<%= render 'shared/error.html.erb' %>


<div class="col-md-4 col-md-offset-4">
<h1 class="text-center">Create a new cat!</h1>
<form action="<%= cats_url %>" method="POST" role="form">
  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

  <div class="form-group">
  <label for="cat_name">Name</label>
  <input type="text" 
        name="cat[name]" 
        id="cat_name" 
        value="<%= @cat.name %>"
        class="form-control"
        placeholder="Name">
  <div>
    
   <fieldset class="sex-fieldset"> 
   <legend class="sex-field">Sex</legend>
        
  <div class="radio form-control">
 
  <% Cat::SEX.each do |sex| %>
    <label for="cat_sex">
    <input type="radio"
           name="cat[sex]"
           value="<%= sex %>"
           <%= "checked" if @cat.sex == sex %>
           id="cat_sex">
      <%= sex == "M" ? "Male" : "Female"%>
    </label>
  <% end %>
</div>
</fieldset>
 
  <label for="cat_color">Color</label>
  <select name="cat[color]" id="cat_color" class="form-control">
    <option></option>
    <% Cat::COLOR.each do |color| %>
      <option 
        value="<%= color %>" 
        <%= "selected" if @cat.color == color %>>
        <%= color %>
      </option>
    <% end %>  
  </select>
  <br>
  
  <label for="cat_birth_date">Birthdate</label>
  <% today = Date.today%>
  <input type="date"
         name="cat[birth_date]"
         value="<%= @cat.birth_date %>"
         max="<%= "#{today.year}-#{today.month}-#{today.day}"%>"
         class="form-control"
         id="cat_birth_date" >
  <br>
  
  <label for="cat_description">Description</label>
  <textarea name="cat[description]"
            id="cat_description"
            class="form-control"
            placeholder="Enter description"><%= @cat.description %></textarea>
  <br>
  
  <button type="submit" class="btn btn-primary btn-lg col-md-offset-4">Create the cat!</button>
</form>

<div>

app/views/cats/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6"><h1><%= @cat.name %></h1></div><div class="col-md-6"><span class="pull-right"><%= gravatar_for @cat %></span></div>
  </div>
</div>
<form action="<%= cat_url(@cat) %> " class="button_to" method="post">
  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">
  
  <div>
    <input name="_method" type="hidden" value="delete">
    <button type="submit" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-remove"></span> Delete</button>
    
    <a href="<%= edit_cat_url(@cat) %>" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-wrench"></span> Edit</a>
    
  </div>
</form>
<hr>

<div class="table_name">Cat Info</div>


<table class="table">
  <thead>
    <th>Birthdate</th>
    <th>Age</th>
    <th>Color</th>
    <th>Sex</th>
    <th>Description</th>
  </thead>
  
  <tr>
    <td><%= @cat.birth_date %></td>
    <td><%= @cat.age %></td>
    <td><%= @cat.color %></td>
    <td><%= @cat.sex %></td>
    <td><%= @cat.description %></td>
  </tr>
  
</table>

<div class="table_name">Rental Requests

<span class="request"><a href="<%= new_cat_rental_request_url %>" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-plus"></span> New rental request</a></span>
</div>


<table class="table">
  <thead>
    <th>Requester</th>
    <th>Rental start date</th>
    <th>Rental end date</th>
    <th>Status</th>
    <th>Approve</th>
    <th>Deny</th>
    <th>Delete</th>
  </thead>
  
  <% @requests.each do |request|%>
  <tr>
    <td><%= request.user.user_name %></td>
    <td><%= request.start_date %></td>
    <td><%= request.end_date %></td>
    <td><%= request.status %></td>
    <% if request.pending? %>
      <td>
        
        <% if current_user == @cat.owner %>
        <a href="<%= cat_rental_request_approve_url(request) %>" 
          class="btn btn-default btn-xs">
          <span class="glyphicon glyphicon-ok"></span> 
          Approve
        </a>
        <% end %>
      </td>
      <td>
        <% if current_user == @cat.owner %>
          <a href="<%= cat_rental_request_deny_url(request) %>" 
          class="btn btn-default btn-xs">
          <span class="glyphicon glyphicon-remove"></span> 
          Deny
        </a>
        <% end %>
        </td>
    <% else %>
      <td></td>
      <td></td>
    <% end %>
    <td>

             
    <form action="<%= cat_rental_request_url(request) %> " class="button_to" method="post">  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">

      <div>
        <input name="_method" type="hidden" value="delete">
        <button type="submit" class="btn btn-default btn-xs"><span class="glyphicon glyphicon-trash"></span> Delete Request</button>
      </div>
    </form>         
             
             
    </td>
  </tr>
  <% end %>
</table>